package org.example.reportsworskhopgft.eventlog.domain;

public enum EventType {
    TIME_ADVANCED,
    DELIVERY_CREATED,
    DELIVERY_COMPLETED,
    TRUCK_REGISTERED,
    TRUCK_STATUS_CHANGED,
    TRUCK_POSITION_UPDATED,
    RECIPE_REGISTERED,
    PRODUCTION_ORDER_CREATED,
    PRODUCTION_ORDER_STARTED,
    PRODUCTION_ORDER_BLOCKED,
    PRODUCTION_ORDER_COMPLETED,
    REPLENISHMENT_REQUESTED,
    WAREHOUSE_STOCK_CHANGED
}
