package org.example.reportsworskhopgft.eventlog.domain;

public enum EventType {
    FACTORY_ORDER_CREATED,
    FACTORY_ORDER_BLOCKED,
    FACTORY_ORDER_COMPLETED,
    WAREHOUSE_REPLENISHMENT,
    DELIVERY_CREATED,
    DELIVERY_COMPLETED,
    TRUCK_DEPARTED,
    TRUCK_ARRIVED,
    TIME_ADVANCED,

    TRUCK_REGISTERED,
    TRUCK_STATUS_CHANGED,
    TRUCK_POSITION_UPDATED,
    RECIPE_REGISTERED,
    PRODUCTION_ORDER_CREATED,
    PRODUCTION_ORDER_STARTED,
    PRODUCTION_ORDER_BLOCKED,
    PRODUCTION_ORDER_COMPLETED,
    REPLENISHMENT_REQUESTED,
    PRODUCTION_RECIPE_REGISTERED,
    PRODUCTION_FACTORY_REGISTERED,
    WAREHOUSE_STOCK_CHANGED
}
