spring.application.name=reports-worskhop-gft
# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL_ENABLED:false}

spring.rabbitmq.listener.simple.missing-queues-fatal=false
spring.rabbitmq.listener.direct.missing-queues-fatal=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/reporting_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=none

#LiquiBase
spring.liquibase.enabled=true 
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
