spring.application.name=reports-worskhop-gft
# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL_ENABLED:false}

spring.rabbitmq.listener.simple.missing-queues-fatal=false
spring.rabbitmq.listener.direct.missing-queues-fatal=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/reporting_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=none

#LiquiBase
#spring.liquibase.enabled=true
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#logging.level.liquibase=DEBUG
#spring.main.allow-bean-definition-overriding=true
spring.liquibase.show-summary=VERBOSE



# Muestra detalles (Rabbit, DB, Disco) en el endpoint de salud
management.endpoint.health.show-details=always

# Expone todos los endpoints de Actuator por HTTP (Métricas, Info, Env)
management.endpoints.web.exposure.include=*

# Opcional: Para que el JSON se vea ordenado en el navegador
spring.jackson.serialization.indent_output=true
