spring.application.name=reports-worskhop-gft
# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/reporting_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate

